export const GET_SEARCH_START_REQUEST = 'GET_SEARCH_START_REQUEST';
export const GET_SEARCH_SUCCESS= 'GET_SEARCH_ITEMS';
export const GET_SEARCH_FAIL= 'GET_SEARCH_FAIL';
export const GET_SEARCH_NO_ITEMS= 'GOT_NO_SEARCH_RESULTS';

export const GET_IMG_START_REQUEST= 'GET_IMG_START_REQUEST';
export const GET_IMG_SUCCESS= 'GET_IMG_ITEMS';
export const GET_IMG_FAIL= 'GET_IMG_FAIL';
export const GET_IMG_NO_ITEMS= 'GOT_NO_IMG';


export const CHANGE_PAGE: string = 'CHANGE_PAGE';
export const CHANGE_LIMIT: string = 'CHANGE_LIMIT';